project:
    # 项目路径
    path: /Users/tengchong/Workspaces/gitee/easy-frame/easy-admin
    version: 1.0
    login:
        remember: true # 是否开启记住我功能,安全性要求比较高的系统请改为false
        remember-invalidate-time: 2592000 # 记住我过期时间 默认30天 单位: 秒
        remember-security: true # 开启记住我功能,敏感操作仍要客户登录 比如 支付/删除/审核
        verification-code: true # 是否开启验证码
        attempts: 5 # 登录是密码错误尝试次数,超过5次后会被锁定
        lock-length: 600 # 锁定时长 单位：秒
    file-upload-path: /Users/tengchong/Development/upload/easy-frame # 文件上传路径(不要写以~开头的路径会导致无法访问)
    session-invalidate-time: 1800 # session失效时间 单位：秒
    session-validation-interval: 1800 # 设置session失效的扫描时间, 清理用户直接关闭浏览器造成的孤立会话 默认为 30分钟
server:
    port: 9080
spring:
    datasource:
        druid:
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://localhost:3306/easy-frame?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMulQueries=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
            db-name: easy-frame
            password: 123456
            username: root
# beetl
beetl:
    #是否检测文件变化,生成环境勿配置
    resource-auto-check: true
# mybatis
mybatis-plus:
    global-config:
        # 刷新mapping文件,生成环境勿配置
        refresh: true